"""add water_requirement_estimates table

Revision ID: 036559e5b1a3
Revises: a74f3a2ecb87
Create Date: 2026-09-27 15:52:49.887434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036559e5b1a3'
down_revision = 'a74f3a2ecb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_requirement_estimates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('crop', sa.String(length=120), nullable=False),
    sa.Column('land_area_acres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('crop_stage', sa.String(length=120), nullable=False),
    sa.Column('stage_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('base_liters_per_acre', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available_water_liters', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remaining_water_liters', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('water_balance_liters', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_sufficient', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_requirement_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_requirement_estimates_farmer_profile_id'), ['farmer_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_requirement_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_requirement_estimates_farmer_profile_id'))

    op.drop_table('water_requirement_estimates')
    # ### end Alembic commands ###
