"""add farmer crops and water allocation tables

Revision ID: 47a5fe46c902
Revises: 036559e5b1a3
Create Date: 2026-09-27 18:33:40.015977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a5fe46c902'
down_revision = '036559e5b1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_crops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=120), nullable=False),
    sa.Column('area_acres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('crop_stage', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('area_acres > 0', name='ck_farmer_crops_positive_area'),
    sa.CheckConstraint('priority >= 1', name='ck_farmer_crops_valid_priority'),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_crops_farmer_profile_id'), ['farmer_profile_id'], unique=False)

    op.create_table('water_allocation_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('total_budget_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('already_used_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_water_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_allocated_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unallocated_water_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('already_used_liters >= 0', name='ck_alloc_plan_nonneg_used'),
    sa.CheckConstraint('remaining_water_liters >= 0', name='ck_alloc_plan_nonneg_remaining'),
    sa.CheckConstraint('total_allocated_liters <= remaining_water_liters', name='ck_alloc_plan_allocated_le_remaining'),
    sa.CheckConstraint('total_allocated_liters >= 0', name='ck_alloc_plan_nonneg_allocated'),
    sa.CheckConstraint('total_budget_liters >= 0', name='ck_alloc_plan_nonneg_budget'),
    sa.CheckConstraint('unallocated_water_liters >= 0', name='ck_alloc_plan_nonneg_unallocated'),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_allocation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_allocation_plans_farmer_profile_id'), ['farmer_profile_id'], unique=False)

    op.create_table('water_allocation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('crop_name', sa.String(length=120), nullable=False),
    sa.Column('area_acres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocated_liters', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percentage_of_remaining', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('allocated_liters >= 0', name='ck_alloc_item_nonneg_liters'),
    sa.CheckConstraint('area_acres > 0', name='ck_alloc_item_positive_area'),
    sa.CheckConstraint('percentage_of_remaining >= 0', name='ck_alloc_item_nonneg_pct'),
    sa.ForeignKeyConstraint(['plan_id'], ['water_allocation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_allocation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_allocation_items_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_allocation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_allocation_items_plan_id'))

    op.drop_table('water_allocation_items')
    with op.batch_alter_table('water_allocation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_allocation_plans_farmer_profile_id'))

    op.drop_table('water_allocation_plans')
    with op.batch_alter_table('farmer_crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_crops_farmer_profile_id'))

    op.drop_table('farmer_crops')
    # ### end Alembic commands ###
