"""add soil_analysis_reports table

Revision ID: 8d80509147e2
Revises: 47a5fe46c902
Create Date: 2026-09-27 19:06:21.230671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d80509147e2'
down_revision = '47a5fe46c902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('apparent_soil_characteristics', sa.Text(), nullable=False),
    sa.Column('possible_moisture_condition', sa.String(length=160), nullable=False),
    sa.Column('visible_issues', sa.JSON(), nullable=False),
    sa.Column('recommended_next_steps', sa.JSON(), nullable=False),
    sa.Column('uncertainty_and_limitations', sa.Text(), nullable=False),
    sa.Column('requires_laboratory_testing', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_te', sa.Text(), nullable=False),
    sa.Column('image_mime_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soil_analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soil_analysis_reports_farmer_profile_id'), ['farmer_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_analysis_reports_farmer_profile_id'))

    op.drop_table('soil_analysis_reports')
    # ### end Alembic commands ###
