"""add is_read to weather_alerts

Revision ID: a74f3a2ecb87
Revises: e4b209d6731f
Create Date: 2026-09-27 15:39:35.114296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74f3a2ecb87'
down_revision = 'e4b209d6731f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_alerts', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
